#freemaker 配置
spring: 
  freemarker:
    request-context-attribute: req
    allow-request-override: false 
    enabled: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .html
    template-loader-path: classpath:/templates/
    expose-spring-macro-helpers: false

#mybatis配置
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml
    
#pagehelper插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql
  auto-runtime-dialect: "true"

server:
  tomcat:
    max-threads: 1000
    accept-count: 1100
    min-spare-threads: 200
    max-connections: 1000
    uri-encoding: UTF-8
    
logging:
  level:
    com.zzhb.zzoa.mapper: DEBUG
    org.springframework.scheduling: INFO
 
   
props: 
  demo: demo
  loginUrl: /login
  globalSessionTimeout: 43200000 #session过期时间
  cookemaxage: 43200000