#freemaker 配置
spring: 
  freemarker:
    request-context-attribute: req
    allow-request-override: false
    allow-session-override: true 
    enabled: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .html
    template-loader-path: classpath:/templates/
    expose-spring-macro-helpers: false
  activiti:  #activiti 配置  
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    async-executor-activate: false
    history-level: full
    rest-api-enabled: true
    rest-api-mapping: /ac/**
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:${props.temp-path}
    

#mybatis配置
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml
    
#pagehelper插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql
  auto-runtime-dialect: "true"

server:
  tomcat:
    max-threads: 1000
    accept-count: 1100
    min-spare-threads: 200
    max-connections: 1000
    uri-encoding: UTF-8
    
logging:
  level:
    com.zzhb.zzoa.mapper: DEBUG
    org.springframework.scheduling: INFO

   
props: 
  loginUrl: /login
  cookiename: ZZOA
  globalSessionTimeout: 43200000 #session过期时间
  temp-path: C:/download