spring: 
  profiles:
    active: dev
---

spring: 
  profiles: dev
  datasource: 
    username: root
    password: 123456
    url: jdbc:mysql://47.104.13.138:3306/dc_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    remove-abandoned: true
    remove-abandoned-timeout: 300
    log-abandoned: false
    initialization-mode: embedded
  redis: 
    database: 1
    host: 47.104.13.138
    port: 6379
    timeout: 0
    password: 123321
    pool:
      max-idle: 10
      max-wait: -1
      min-idle: 2
      max-active: 20
    
server:
  port: 8888

#netty配置
netty: 
  tcp: 
    port: 9090
  backlog: 1024
  thread: 
    boss: 1
    worker: 4

dciurl: http://127.0.0.1:9091/

---

spring: 
  profiles: test
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.104.13.138:3306/dc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    remove-abandoned: true
    remove-abandoned-timeout: 300
    log-abandoned: false
    initialization-mode: embedded
  redis: 
    database: 0
    host: 47.104.13.138
    port: 6379
    timeout: 0
    password: 123321
    pool:
      max-idle: 10
      max-wait: -1
      min-idle: 2
      max-active: 20
    
server:
  port: 19999


#netty配置
netty: 
  tcp: 
    port: 19090
  backlog: 1024
  thread: 
    boss: 1
    worker: 4

dciurl: http://47.104.13.138:8888/
    
---

spring: 
  profiles: prod
  datasource: 
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    remove-abandoned: true
    remove-abandoned-timeout: 300
    log-abandoned: false
    initialization-mode: embedded
  redis: 
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    password: 123321
    pool:
      max-idle: 10
      max-wait: -1
      min-idle: 2
      max-active: 20
    
server:
  port: 8080

#netty配置
netty: 
  tcp: 
    port: 9090
  backlog: 1024
  thread: 
    boss: 1
    worker: 4

dciurl: http://47.104.13.138:8888/